definitions: 
  env_versions: &env_versions
    flutter: stable
  scripts:
    - &get_flutter_packages
      name: Get Flutter packages
      script: |
        flutter packages pub get
    - &analyze_flutter
      name: Flutter analyze
      script: |
        flutter analyze
    - &flutter_unit_tests
      name: Flutter unit tests
      script: |
        flutter test
    - &flutter_build_webapp
      name: Flutter build webapp
      script: |
        flutter build web --release
        cd build/web
        7z a -r ../web.zip ./*
  email_develop: &email_develop
    email:
      recipients:
        - user_3@example.com
        - user_4@example.com
        - ivan@codemagic.io
  slack_publish: &slack_publish
    slack:
      channel: "#builds"
workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      groups:
        - keystore_credentials
        - google_play
      vars:
        PACKAGE_NAME: "io.codemagic.ivan"
        GOOGLE_PLAY_TRACK: internal
        submit_as_draft: true
      flutter: stable  #or we can write << : *env_versions
      ios_signing:
        distribution_type: development # or: ad_hoc | app_store | enterprise
        bundle_identifier: io.codemagic.ivan
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build AAB with Flutter
        script: |   
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false
      <<: *email_develop
      <<: *slack_publish
      scripts:
        - echo 'Post-publish script'
  web-workflow:
    name: Web app workflow
    max_build_duration: 10
    environment:
      << : *env_versions
      groups:
        - keystore_credentials
        - google_play
    scripts:
      - *get_flutter_packages
      - *analyze_flutter
      - *flutter_unit_tests
      - *flutter_build_webapp
    artifacts:
      - build/web.zip
      - flutter_drive.log
    publishing:
      <<: *email_develop
  ios-yaml-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: ivan-codemagic-demo
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: false
    environment:
      groups:
        - keystore_credentials
        - google_play
      ios_signing:
        distribution_type: app_store
        bundle_identifier: io.codemagic.ivanyaml
      vars:
        APP_ID: 6738692730 # <-- Use the TestFlight Apple id number (An automatically generated ID assigned to your app) found under General > App Information > Apple ID.
      flutter: stable
    scripts:
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles
      - name: Get Flutter packages
        script: | 
          flutter pub get
      - name: Install pods
        script: | 
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: | 
          flutter analyze
      - name: Flutter unit tests
        script: | 
          flutter test
        ignore_failure: true
      - name: Flutter build ipa
        script: | 
          BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_ID") + 1))
          flutter build ipa --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - ivan@codemagic.io
          - user_2@example.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration

        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: false
        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
          - group name 1
          - group name 2

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false
